services:
  - type: worker
    name: kucoin-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: KUCOIN_API_KEY
        sync: false
      - key: KUCOIN_API_SECRET
        sync: false
      - key: KUCOIN_API_PASSPHRASE
        sync: false
